import streamlit as st
import pandas as pd
import plotly.express as px


def show():

    st.title("🧠 ML Intrusion Detection (XGBoost)")

    st.markdown("""
### XGBoost-based Intrusion Detection System

The model is trained offline using the **CIC-IDS2017** benchmark dataset.

Its predicted attack probabilities are intended to serve as an additional trust evidence source for the proposed Trust Evidence Fusion Layer (TEFL).
""")

    metrics = pd.read_csv("results/xgboost_metrics.csv")

    st.subheader("Classification Performance")

    st.table(metrics)

    fig = px.bar(
        metrics,
        x="Metric",
        y="Value",
        color="Metric",
        text="Value",
        title="XGBoost Performance"
    )

    fig.update_traces(
        texttemplate="%{text:.4f}",
        textposition="outside"
    )

    fig.update_layout(
        template="plotly_dark",
        showlegend=False,
        height=500
    )

    st.plotly_chart(fig, use_container_width=True)

    st.success("""
Dataset : CIC-IDS2017

Training Samples : 2,016,638

Testing Samples : 504,160

Classifier : XGBoost

Attack probabilities generated by this model can be integrated into the Trust Evidence Fusion Layer as an additional trust evidence source.
""")